server:
    build: bin/evennia
    workdir: /usr/src/larsethia
    volumes:
      - .:/usr/src/larsethia
    ports:
      - 4000:4000
      - 80:8000
      - 8001:8001
backup:
    build: bin/backup
    workdir: /usr/src/larsethia
    volumes:
      - .:/usr/src/larsethia
