server:
    build: dockerfiles/
    dockerfile: evennia
    working_dir: /usr/src/larsethia
    volumes:
      - .:/usr/src/larsethia
    ports:
      - 4000:4000
      - 80:8000
      - 8001:8001
