QUEST_COMPLETE = 0
QUEST_DIR = "world.quests."
QUEST_NAME_CONST = 'QUEST_NAME'
QUEST_DESC_CONST = 'QUEST_DESC'

IDLE_INTERVAL = 5.0

RESPAWN_RATE_DEFAULT = 300
RESPAWN_TICK_RATE = 5

TAG_CATEGORY_BUILDING = "building"
